import type { Metadata } from "next";
import "../globals.css";
import Link from "next/link";
import { headers } from "next/headers";

export const metadata: Metadata = {
  title: "Neebal Dossier Application",
  description: "Generated by Nikhil More",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers(); 
  const pathname = headersList.get('x-pathname') || '';

  const isUserRoute = pathname.startsWith('/user');

  return (
    <html lang="en">
      <body className="bg-gray-50 min-h-screen flex flex-col">
        {/* Header */}
        {!isUserRoute && (
          <header className="bg-white shadow-md">
            <div className="container mx-auto px-6 py-4 flex justify-between items-center">
              {/* Logo and App Name */}
              <div className="flex items-center space-x-3">
                <span className="text-2xl font-bold text-blue-700 font-mono">
                  Neebal Dossier
                </span>
              </div>
              {/* Navigation Menu */}
              <nav className="space-x-6">
                <Link
                  href="/"
                  className="text-gray-600 hover:text-blue-700 text-lg font-medium"
                >
                  Home
                </Link>
                <Link
                  href="/register"
                  className="text-gray-600 hover:text-blue-700 text-lg font-medium"
                >
                  Register
                </Link>
                <Link
                  href="/login"
                  className="text-gray-600 hover:text-blue-700 text-lg font-medium"
                >
                  Login
                </Link>
              </nav>
            </div>
          </header>
        )}

        {/* Main Content */}
        <main className="flex-1 container mx-auto px-6 py-10">{children}</main>

        {/* Footer (Optional) */}
        {!isUserRoute && (
          <footer className="bg-white shadow-inner py-4 text-center text-sm text-gray-500">
            © 2025 Neebal Technologies. All rights reserved.
          </footer>
        )}
      </body>
    </html>
  );
}
