import type { Metadata } from "next";
import "../globals.css";
import Link from "next/link";
import { headers } from "next/headers";

export const metadata: Metadata = {
  title: "Neebal Dossier Application",
  description: "Generated by Nikhil More",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const pathname = headersList.get("x-pathname") || "";
  const isUserRoute = pathname.startsWith("/user");

  return (
    <html lang="en">
      <body className="bg-[#111827] min-h-screen flex flex-col font-sans text-[#f9fafb]">
        {/* Header */}
        {!isUserRoute && (
          <header className="bg-[#1f2937] shadow-md sticky top-0 z-50">
            <div className="container mx-auto px-8 py-5 flex justify-between items-center">
              {/* Logo and App Name */}
              <div className="flex items-center space-x-3">
                <span className="text-3xl font-extrabold text-[#2563eb] tracking-wide">
                  Neebal Dossier
                </span>
              </div>

              {/* Navigation Menu */}
              <nav className="flex space-x-8">
                <Link
                  href="/"
                  className="text-[#f9fafb] hover:text-[#60a5fa] text-lg font-medium transition-colors duration-200"
                >
                  Home
                </Link>
                <Link
                  href="/register"
                  className="text-[#f9fafb] hover:text-[#60a5fa] text-lg font-medium transition-colors duration-200"
                >
                  Register
                </Link>
                <Link
                  href="/login"
                  className="text-[#f9fafb] hover:text-[#60a5fa] text-lg font-medium transition-colors duration-200"
                >
                  Login
                </Link>
              </nav>
            </div>
          </header>
        )}

        {/* Main Content */}
        <main className="flex-1 container mx-auto px-8 py-12">{children}</main>

        {/* Footer */}
        {!isUserRoute && (
          <footer className="bg-[#1f2937] shadow-inner py-5 text-center text-sm text-gray-400 border-t border-gray-700">
            © 2025 Neebal Technologies. All rights reserved.
          </footer>
        )}
      </body>
    </html>
  );
}
